# Generated by Django 4.1.3 on 2022-11-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('autorApellido', models.CharField(max_length=40)),
                ('autorNombre', models.CharField(max_length=40)),
                ('publicacion', models.IntegerField()),
                ('contenido', models.CharField(max_length=1200)),
            ],
        ),
    ]
