# Generated by Django 4.1.3 on 2022-12-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='autorApellido',
            new_name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='autorNombre',
        ),
    ]
