# Generated by Django 4.1.3 on 2023-01-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0003_alter_blog_contenido_alter_blog_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categoria',
            field=models.CharField(default='Varios', max_length=40),
            preserve_default=False,
        ),
    ]
