# Generated by Django 4.1.3 on 2023-01-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0004_blog_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores',
            name='mail',
            field=models.EmailField(default='No Disponible', max_length=254),
            preserve_default=False,
        ),
    ]
