# Generated by Django 4.1.3 on 2023-01-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0005_autor_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='desc',
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(default='Varios', max_length=140),
            preserve_default=False,
        ),
    ]
